version: '3.8'

services:
  auth:
    build:
      context: ./services/auth/AuthService
      dockerfile: Dockerfile
    image: authservice:latest
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=auth-db;Port=5432;Database=auth;Username=postgres;Password=password"
    depends_on:
      - auth-db

  auth-db:
    image: postgres:15
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
    - "55432:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data

# Go stakeholders service (no new DB)
  stakeholders:
    build:
      context: ./services/stakeholders
      dockerfile: Dockerfile
    image: stakeholders:latest
    ports:
      - "5001:8080"  # host 5001 -> container 8080
    environment:
      USER_DB_HOST: auth-db
      USER_DB_USER: postgres
      USER_DB_PASS: password
      USER_DB_NAME: auth
      USER_DB_PORT: "5432"
      USER_SERVICE_PORT: "8080"
        # JWT verification
      Jwt__Key: "aiugbherajndfuieajdvnaiuerkjdfnaeui"  # must match Auth
      Jwt__Issuer: "AuthService"
      Jwt__Audience: "AuthServiceClient"
    depends_on:
      - auth
      - auth-db

volumes:
  auth_data:
