version: '3.8'

services:
  auth:
    build:
      context: ./services/auth/AuthService
      dockerfile: Dockerfile
    image: authservice:latest
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=auth-db;Port=5432;Database=auth;Username=postgres;Password=123"
    depends_on:
      - auth-db

  auth-db:
    image: postgres:15
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - auth_data:/var/lib/postgresql/data

# placeholder for future services
#  gateway:
#    build: ./gateway
#    ports: [...]

volumes:
  auth_data:
