version: "3.9"

services:
    auth:
        build:
            context: ./services/auth/AuthService
            dockerfile: Dockerfile
        container_name: "authService"
        image: authservice:latest
        ports:
            - "5000:8080"
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ConnectionStrings__DefaultConnection: "Host=auth-db;Port=5432;Database=auth;Username=postgres;Password=password"
        depends_on:
            - auth-db

    auth-db:
        image: postgres:15
        container_name: "authDatabase"
        environment:
            POSTGRES_DB: auth
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - auth_data:/var/lib/postgresql/data

    blogservice:
        build:
            context: ./services/blog
            dockerfile: Dockerfile
        container_name: blogService
        image: blogservice
        ports:
            - "5100:8080"
        environment:
            - MONGO_URI=mongodb://blogmongodb:27017
        depends_on:
            - blogmongodb

    blogmongodb:
        image: mongo:6
        container_name: blogDatabase
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
# placeholder for future services
#  gateway:
#    build: ./gateway
#    ports: [...]

volumes:
    auth_data:
    mongo-data:
