// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/shopping.proto

package shoppingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_proto_shopping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shopping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_proto_shopping_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Cart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Total         float64                `protobuf:"fixed64,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cart) Reset() {
	*x = Cart{}
	mi := &file_proto_shopping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shopping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_proto_shopping_proto_rawDescGZIP(), []int{1}
}

func (x *Cart) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Cart) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Cart) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AddToCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Item          *OrderItem             `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCartRequest) Reset() {
	*x = AddToCartRequest{}
	mi := &file_proto_shopping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartRequest) ProtoMessage() {}

func (x *AddToCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shopping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartRequest.ProtoReflect.Descriptor instead.
func (*AddToCartRequest) Descriptor() ([]byte, []int) {
	return file_proto_shopping_proto_rawDescGZIP(), []int{2}
}

func (x *AddToCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddToCartRequest) GetItem() *OrderItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type AddToCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCartResponse) Reset() {
	*x = AddToCartResponse{}
	mi := &file_proto_shopping_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartResponse) ProtoMessage() {}

func (x *AddToCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shopping_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartResponse.ProtoReflect.Descriptor instead.
func (*AddToCartResponse) Descriptor() ([]byte, []int) {
	return file_proto_shopping_proto_rawDescGZIP(), []int{3}
}

func (x *AddToCartResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type RemoveFromCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"` // remove first matching tour item
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromCartRequest) Reset() {
	*x = RemoveFromCartRequest{}
	mi := &file_proto_shopping_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromCartRequest) ProtoMessage() {}

func (x *RemoveFromCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shopping_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromCartRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromCartRequest) Descriptor() ([]byte, []int) {
	return file_proto_shopping_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveFromCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveFromCartRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type RemoveFromCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromCartResponse) Reset() {
	*x = RemoveFromCartResponse{}
	mi := &file_proto_shopping_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromCartResponse) ProtoMessage() {}

func (x *RemoveFromCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shopping_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromCartResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromCartResponse) Descriptor() ([]byte, []int) {
	return file_proto_shopping_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveFromCartResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_proto_shopping_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shopping_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_proto_shopping_proto_rawDescGZIP(), []int{6}
}

func (x *GetCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartResponse) Reset() {
	*x = GetCartResponse{}
	mi := &file_proto_shopping_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartResponse) ProtoMessage() {}

func (x *GetCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shopping_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartResponse.ProtoReflect.Descriptor instead.
func (*GetCartResponse) Descriptor() ([]byte, []int) {
	return file_proto_shopping_proto_rawDescGZIP(), []int{7}
}

func (x *GetCartResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type CheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_proto_shopping_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shopping_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_shopping_proto_rawDescGZIP(), []int{8}
}

func (x *CheckoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TourPurchaseToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TourId        string                 `protobuf:"bytes,3,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	TourName      string                 `protobuf:"bytes,4,opt,name=tour_name,json=tourName,proto3" json:"tour_name,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	PurchasedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=purchased_at,json=purchasedAt,proto3" json:"purchased_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourPurchaseToken) Reset() {
	*x = TourPurchaseToken{}
	mi := &file_proto_shopping_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourPurchaseToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourPurchaseToken) ProtoMessage() {}

func (x *TourPurchaseToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shopping_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourPurchaseToken.ProtoReflect.Descriptor instead.
func (*TourPurchaseToken) Descriptor() ([]byte, []int) {
	return file_proto_shopping_proto_rawDescGZIP(), []int{9}
}

func (x *TourPurchaseToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TourPurchaseToken) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TourPurchaseToken) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *TourPurchaseToken) GetTourName() string {
	if x != nil {
		return x.TourName
	}
	return ""
}

func (x *TourPurchaseToken) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TourPurchaseToken) GetPurchasedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PurchasedAt
	}
	return nil
}

type CheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*TourPurchaseToken   `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutResponse) Reset() {
	*x = CheckoutResponse{}
	mi := &file_proto_shopping_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResponse) ProtoMessage() {}

func (x *CheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shopping_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResponse.ProtoReflect.Descriptor instead.
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_shopping_proto_rawDescGZIP(), []int{10}
}

func (x *CheckoutResponse) GetTokens() []*TourPurchaseToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type GetTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokensRequest) Reset() {
	*x = GetTokensRequest{}
	mi := &file_proto_shopping_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokensRequest) ProtoMessage() {}

func (x *GetTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shopping_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokensRequest.ProtoReflect.Descriptor instead.
func (*GetTokensRequest) Descriptor() ([]byte, []int) {
	return file_proto_shopping_proto_rawDescGZIP(), []int{11}
}

func (x *GetTokensRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*TourPurchaseToken   `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokensResponse) Reset() {
	*x = GetTokensResponse{}
	mi := &file_proto_shopping_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokensResponse) ProtoMessage() {}

func (x *GetTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shopping_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokensResponse.ProtoReflect.Descriptor instead.
func (*GetTokensResponse) Descriptor() ([]byte, []int) {
	return file_proto_shopping_proto_rawDescGZIP(), []int{12}
}

func (x *GetTokensResponse) GetTokens() []*TourPurchaseToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

var File_proto_shopping_proto protoreflect.FileDescriptor

const file_proto_shopping_proto_rawDesc = "" +
	"\n" +
	"\x14proto/shopping.proto\x12\bshopping\x1a\x1fgoogle/protobuf/timestamp.proto\"N\n" +
	"\tOrderItem\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"`\n" +
	"\x04Cart\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x05items\x18\x02 \x03(\v2\x13.shopping.OrderItemR\x05items\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x01R\x05total\"T\n" +
	"\x10AddToCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x04item\x18\x02 \x01(\v2\x13.shopping.OrderItemR\x04item\"7\n" +
	"\x11AddToCartResponse\x12\"\n" +
	"\x04cart\x18\x01 \x01(\v2\x0e.shopping.CartR\x04cart\"I\n" +
	"\x15RemoveFromCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\"<\n" +
	"\x16RemoveFromCartResponse\x12\"\n" +
	"\x04cart\x18\x01 \x01(\v2\x0e.shopping.CartR\x04cart\")\n" +
	"\x0eGetCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"5\n" +
	"\x0fGetCartResponse\x12\"\n" +
	"\x04cart\x18\x01 \x01(\v2\x0e.shopping.CartR\x04cart\"*\n" +
	"\x0fCheckoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xc7\x01\n" +
	"\x11TourPurchaseToken\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\atour_id\x18\x03 \x01(\tR\x06tourId\x12\x1b\n" +
	"\ttour_name\x18\x04 \x01(\tR\btourName\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12=\n" +
	"\fpurchased_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vpurchasedAt\"G\n" +
	"\x10CheckoutResponse\x123\n" +
	"\x06tokens\x18\x01 \x03(\v2\x1b.shopping.TourPurchaseTokenR\x06tokens\"+\n" +
	"\x10GetTokensRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"H\n" +
	"\x11GetTokensResponse\x123\n" +
	"\x06tokens\x18\x01 \x03(\v2\x1b.shopping.TourPurchaseTokenR\x06tokens2\xf5\x02\n" +
	"\x0fShoppingService\x12D\n" +
	"\tAddToCart\x12\x1a.shopping.AddToCartRequest\x1a\x1b.shopping.AddToCartResponse\x12S\n" +
	"\x0eRemoveFromCart\x12\x1f.shopping.RemoveFromCartRequest\x1a .shopping.RemoveFromCartResponse\x12>\n" +
	"\aGetCart\x12\x18.shopping.GetCartRequest\x1a\x19.shopping.GetCartResponse\x12A\n" +
	"\bCheckout\x12\x19.shopping.CheckoutRequest\x1a\x1a.shopping.CheckoutResponse\x12D\n" +
	"\tGetTokens\x12\x1a.shopping.GetTokensRequest\x1a\x1b.shopping.GetTokensResponseB\\ZZgithub.com/zopuu/soa-team-20/Backend/services/shopping_service/proto/shoppingpb;shoppingpbb\x06proto3"

var (
	file_proto_shopping_proto_rawDescOnce sync.Once
	file_proto_shopping_proto_rawDescData []byte
)

func file_proto_shopping_proto_rawDescGZIP() []byte {
	file_proto_shopping_proto_rawDescOnce.Do(func() {
		file_proto_shopping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shopping_proto_rawDesc), len(file_proto_shopping_proto_rawDesc)))
	})
	return file_proto_shopping_proto_rawDescData
}

var file_proto_shopping_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_shopping_proto_goTypes = []any{
	(*OrderItem)(nil),              // 0: shopping.OrderItem
	(*Cart)(nil),                   // 1: shopping.Cart
	(*AddToCartRequest)(nil),       // 2: shopping.AddToCartRequest
	(*AddToCartResponse)(nil),      // 3: shopping.AddToCartResponse
	(*RemoveFromCartRequest)(nil),  // 4: shopping.RemoveFromCartRequest
	(*RemoveFromCartResponse)(nil), // 5: shopping.RemoveFromCartResponse
	(*GetCartRequest)(nil),         // 6: shopping.GetCartRequest
	(*GetCartResponse)(nil),        // 7: shopping.GetCartResponse
	(*CheckoutRequest)(nil),        // 8: shopping.CheckoutRequest
	(*TourPurchaseToken)(nil),      // 9: shopping.TourPurchaseToken
	(*CheckoutResponse)(nil),       // 10: shopping.CheckoutResponse
	(*GetTokensRequest)(nil),       // 11: shopping.GetTokensRequest
	(*GetTokensResponse)(nil),      // 12: shopping.GetTokensResponse
	(*timestamppb.Timestamp)(nil),  // 13: google.protobuf.Timestamp
}
var file_proto_shopping_proto_depIdxs = []int32{
	0,  // 0: shopping.Cart.items:type_name -> shopping.OrderItem
	0,  // 1: shopping.AddToCartRequest.item:type_name -> shopping.OrderItem
	1,  // 2: shopping.AddToCartResponse.cart:type_name -> shopping.Cart
	1,  // 3: shopping.RemoveFromCartResponse.cart:type_name -> shopping.Cart
	1,  // 4: shopping.GetCartResponse.cart:type_name -> shopping.Cart
	13, // 5: shopping.TourPurchaseToken.purchased_at:type_name -> google.protobuf.Timestamp
	9,  // 6: shopping.CheckoutResponse.tokens:type_name -> shopping.TourPurchaseToken
	9,  // 7: shopping.GetTokensResponse.tokens:type_name -> shopping.TourPurchaseToken
	2,  // 8: shopping.ShoppingService.AddToCart:input_type -> shopping.AddToCartRequest
	4,  // 9: shopping.ShoppingService.RemoveFromCart:input_type -> shopping.RemoveFromCartRequest
	6,  // 10: shopping.ShoppingService.GetCart:input_type -> shopping.GetCartRequest
	8,  // 11: shopping.ShoppingService.Checkout:input_type -> shopping.CheckoutRequest
	11, // 12: shopping.ShoppingService.GetTokens:input_type -> shopping.GetTokensRequest
	3,  // 13: shopping.ShoppingService.AddToCart:output_type -> shopping.AddToCartResponse
	5,  // 14: shopping.ShoppingService.RemoveFromCart:output_type -> shopping.RemoveFromCartResponse
	7,  // 15: shopping.ShoppingService.GetCart:output_type -> shopping.GetCartResponse
	10, // 16: shopping.ShoppingService.Checkout:output_type -> shopping.CheckoutResponse
	12, // 17: shopping.ShoppingService.GetTokens:output_type -> shopping.GetTokensResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_shopping_proto_init() }
func file_proto_shopping_proto_init() {
	if File_proto_shopping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shopping_proto_rawDesc), len(file_proto_shopping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shopping_proto_goTypes,
		DependencyIndexes: file_proto_shopping_proto_depIdxs,
		MessageInfos:      file_proto_shopping_proto_msgTypes,
	}.Build()
	File_proto_shopping_proto = out.File
	file_proto_shopping_proto_goTypes = nil
	file_proto_shopping_proto_depIdxs = nil
}
