receivers:
  docker_stats:
    endpoint: unix:///var/run/docker.sock
    collection_interval: 10s
  hostmetrics:
    collection_interval: 10s
    scrapers: { cpu: {}, memory: {}, filesystem: {}, network: {}, load: {} }

processors:
  batch: {}

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"
    # 👇 THIS makes resource attrs (container.name, container.id, image, etc.)
    #    appear as Prometheus labels (container_name, container_id, ...)
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    metrics:
      receivers: [docker_stats, hostmetrics]
      processors: [batch]
      exporters: [prometheus]
