receivers:
  otlp:
    protocols: { grpc: {}, http: {} }

exporters:
  otlphttp/tempo:
    endpoint: http://tempo:4318
  logging:
    loglevel: debug

processors:
  batch: {}
  memory_limiter: { check_interval: 5s, limit_percentage: 75 }

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging, otlphttp/tempo]
