server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /positions/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: ['__meta_docker_container_id']
        target_label: '__path__'
        replacement: '/var/lib/docker/containers/$1/$1-json.log'
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: compose_service

    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            level: level
            msg: msg
            service: service
            method: method
            path: path
            status: status
            latency_ms: latency_ms
            request_id: request_id
            trace_id: trace_id
            RequestMethod: RequestMethod
            RequestPath: RequestPath
            StatusCode: StatusCode
            Elapsed: Elapsed
            msg_template: '["@mt"]'   # fix za Serilog "@mt"
      - labels:
          service:
          level:
          status:
          request_id:
          trace_id:
          container:
          compose_service:
