version: "3.9"

services:
  followers-db:
    image: neo4j:5
    container_name: followers-neo4j
    restart: always
    ports:
      - "7688:7687"
      - "7475:7474"
    environment:
      - NEO4J_AUTH=neo4j/followersPass
    volumes:
      - followers_data:/data
    networks:
      - backendnet

  followers-service:
    build:
      context: .  # path to your Dockerfile
    container_name: followers-service
    depends_on:
      - followers-db
    ports:
      - "50051:50051"
    networks:
      - backendnet

volumes:
  followers_data:

networks:
  backendnet:
    driver: bridge