// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/tour.proto

package tourpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums based on the Go model
type TourStatus int32

const (
	TourStatus_TOUR_STATUS_UNSPECIFIED TourStatus = 0
	TourStatus_TOUR_STATUS_DRAFT       TourStatus = 1
	TourStatus_TOUR_STATUS_PUBLISHED   TourStatus = 2
	TourStatus_TOUR_STATUS_ARCHIVED    TourStatus = 3
)

// Enum value maps for TourStatus.
var (
	TourStatus_name = map[int32]string{
		0: "TOUR_STATUS_UNSPECIFIED",
		1: "TOUR_STATUS_DRAFT",
		2: "TOUR_STATUS_PUBLISHED",
		3: "TOUR_STATUS_ARCHIVED",
	}
	TourStatus_value = map[string]int32{
		"TOUR_STATUS_UNSPECIFIED": 0,
		"TOUR_STATUS_DRAFT":       1,
		"TOUR_STATUS_PUBLISHED":   2,
		"TOUR_STATUS_ARCHIVED":    3,
	}
)

func (x TourStatus) Enum() *TourStatus {
	p := new(TourStatus)
	*p = x
	return p
}

func (x TourStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tour_proto_enumTypes[0].Descriptor()
}

func (TourStatus) Type() protoreflect.EnumType {
	return &file_proto_tour_proto_enumTypes[0]
}

func (x TourStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourStatus.Descriptor instead.
func (TourStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{0}
}

type TourDifficulty int32

const (
	TourDifficulty_TOUR_DIFFICULTY_UNSPECIFIED  TourDifficulty = 0
	TourDifficulty_TOUR_DIFFICULTY_BEGINNER     TourDifficulty = 1
	TourDifficulty_TOUR_DIFFICULTY_INTERMEDIATE TourDifficulty = 2
	TourDifficulty_TOUR_DIFFICULTY_ADVANCED     TourDifficulty = 3
	TourDifficulty_TOUR_DIFFICULTY_PRO          TourDifficulty = 4
)

// Enum value maps for TourDifficulty.
var (
	TourDifficulty_name = map[int32]string{
		0: "TOUR_DIFFICULTY_UNSPECIFIED",
		1: "TOUR_DIFFICULTY_BEGINNER",
		2: "TOUR_DIFFICULTY_INTERMEDIATE",
		3: "TOUR_DIFFICULTY_ADVANCED",
		4: "TOUR_DIFFICULTY_PRO",
	}
	TourDifficulty_value = map[string]int32{
		"TOUR_DIFFICULTY_UNSPECIFIED":  0,
		"TOUR_DIFFICULTY_BEGINNER":     1,
		"TOUR_DIFFICULTY_INTERMEDIATE": 2,
		"TOUR_DIFFICULTY_ADVANCED":     3,
		"TOUR_DIFFICULTY_PRO":          4,
	}
)

func (x TourDifficulty) Enum() *TourDifficulty {
	p := new(TourDifficulty)
	*p = x
	return p
}

func (x TourDifficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourDifficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tour_proto_enumTypes[1].Descriptor()
}

func (TourDifficulty) Type() protoreflect.EnumType {
	return &file_proto_tour_proto_enumTypes[1]
}

func (x TourDifficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourDifficulty.Descriptor instead.
func (TourDifficulty) EnumDescriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{1}
}

type TransportType int32

const (
	TransportType_TRANSPORT_TYPE_UNSPECIFIED TransportType = 0
	TransportType_TRANSPORT_TYPE_WALKING     TransportType = 1
	TransportType_TRANSPORT_TYPE_BICYCLE     TransportType = 2
	TransportType_TRANSPORT_TYPE_BUS         TransportType = 3
)

// Enum value maps for TransportType.
var (
	TransportType_name = map[int32]string{
		0: "TRANSPORT_TYPE_UNSPECIFIED",
		1: "TRANSPORT_TYPE_WALKING",
		2: "TRANSPORT_TYPE_BICYCLE",
		3: "TRANSPORT_TYPE_BUS",
	}
	TransportType_value = map[string]int32{
		"TRANSPORT_TYPE_UNSPECIFIED": 0,
		"TRANSPORT_TYPE_WALKING":     1,
		"TRANSPORT_TYPE_BICYCLE":     2,
		"TRANSPORT_TYPE_BUS":         3,
	}
)

func (x TransportType) Enum() *TransportType {
	p := new(TransportType)
	*p = x
	return p
}

func (x TransportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tour_proto_enumTypes[2].Descriptor()
}

func (TransportType) Type() protoreflect.EnumType {
	return &file_proto_tour_proto_enumTypes[2]
}

func (x TransportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportType.Descriptor instead.
func (TransportType) EnumDescriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{2}
}

// Tour message based on the Go model
type Tour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    TourDifficulty         `protobuf:"varint,5,opt,name=difficulty,proto3,enum=tour.TourDifficulty" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        TourStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=tour.TourStatus" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	Distance      float64                `protobuf:"fixed64,9,opt,name=distance,proto3" json:"distance,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	ArchivedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"`
	Duration      float64                `protobuf:"fixed64,12,opt,name=duration,proto3" json:"duration,omitempty"`
	TransportType TransportType          `protobuf:"varint,13,opt,name=transport_type,json=transportType,proto3,enum=tour.TransportType" json:"transport_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tour) Reset() {
	*x = Tour{}
	mi := &file_proto_tour_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tour) ProtoMessage() {}

func (x *Tour) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tour.ProtoReflect.Descriptor instead.
func (*Tour) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{0}
}

func (x *Tour) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tour) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Tour) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Tour) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tour) GetDifficulty() TourDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return TourDifficulty_TOUR_DIFFICULTY_UNSPECIFIED
}

func (x *Tour) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Tour) GetStatus() TourStatus {
	if x != nil {
		return x.Status
	}
	return TourStatus_TOUR_STATUS_UNSPECIFIED
}

func (x *Tour) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Tour) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Tour) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Tour) GetArchivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchivedAt
	}
	return nil
}

func (x *Tour) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Tour) GetTransportType() TransportType {
	if x != nil {
		return x.TransportType
	}
	return TransportType_TRANSPORT_TYPE_UNSPECIFIED
}

// Request and Response messages
type CreateTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    TourDifficulty         `protobuf:"varint,4,opt,name=difficulty,proto3,enum=tour.TourDifficulty" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	TransportType TransportType          `protobuf:"varint,6,opt,name=transport_type,json=transportType,proto3,enum=tour.TransportType" json:"transport_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTourRequest) Reset() {
	*x = CreateTourRequest{}
	mi := &file_proto_tour_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourRequest) ProtoMessage() {}

func (x *CreateTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourRequest.ProtoReflect.Descriptor instead.
func (*CreateTourRequest) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTourRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CreateTourRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTourRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTourRequest) GetDifficulty() TourDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return TourDifficulty_TOUR_DIFFICULTY_UNSPECIFIED
}

func (x *CreateTourRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateTourRequest) GetTransportType() TransportType {
	if x != nil {
		return x.TransportType
	}
	return TransportType_TRANSPORT_TYPE_UNSPECIFIED
}

type CreateTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTourResponse) Reset() {
	*x = CreateTourResponse{}
	mi := &file_proto_tour_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourResponse) ProtoMessage() {}

func (x *CreateTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourResponse.ProtoReflect.Descriptor instead.
func (*CreateTourResponse) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTourResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

func (x *CreateTourResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTourRequest) Reset() {
	*x = DeleteTourRequest{}
	mi := &file_proto_tour_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTourRequest) ProtoMessage() {}

func (x *DeleteTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTourRequest.ProtoReflect.Descriptor instead.
func (*DeleteTourRequest) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteTourRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTourResponse) Reset() {
	*x = DeleteTourResponse{}
	mi := &file_proto_tour_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTourResponse) ProtoMessage() {}

func (x *DeleteTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTourResponse.ProtoReflect.Descriptor instead.
func (*DeleteTourResponse) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTourResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteTourResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_tour_proto protoreflect.FileDescriptor

const file_proto_tour_proto_rawDesc = "" +
	"\n" +
	"\x10proto/tour.proto\x12\x04tour\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe5\x03\n" +
	"\x04Tour\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x124\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\x0e2\x14.tour.TourDifficultyR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12(\n" +
	"\x06status\x18\a \x01(\x0e2\x10.tour.TourStatusR\x06status\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12\x1a\n" +
	"\bdistance\x18\t \x01(\x01R\bdistance\x12=\n" +
	"\fpublished_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12;\n" +
	"\varchived_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"archivedAt\x12\x1a\n" +
	"\bduration\x18\f \x01(\x01R\bduration\x12:\n" +
	"\x0etransport_type\x18\r \x01(\x0e2\x13.tour.TransportTypeR\rtransportType\"\xee\x01\n" +
	"\x11CreateTourRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x124\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\x0e2\x14.tour.TourDifficultyR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12:\n" +
	"\x0etransport_type\x18\x06 \x01(\x0e2\x13.tour.TransportTypeR\rtransportType\"N\n" +
	"\x12CreateTourResponse\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"#\n" +
	"\x11DeleteTourRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x12DeleteTourResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess*u\n" +
	"\n" +
	"TourStatus\x12\x1b\n" +
	"\x17TOUR_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TOUR_STATUS_DRAFT\x10\x01\x12\x19\n" +
	"\x15TOUR_STATUS_PUBLISHED\x10\x02\x12\x18\n" +
	"\x14TOUR_STATUS_ARCHIVED\x10\x03*\xa8\x01\n" +
	"\x0eTourDifficulty\x12\x1f\n" +
	"\x1bTOUR_DIFFICULTY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TOUR_DIFFICULTY_BEGINNER\x10\x01\x12 \n" +
	"\x1cTOUR_DIFFICULTY_INTERMEDIATE\x10\x02\x12\x1c\n" +
	"\x18TOUR_DIFFICULTY_ADVANCED\x10\x03\x12\x17\n" +
	"\x13TOUR_DIFFICULTY_PRO\x10\x04*\x7f\n" +
	"\rTransportType\x12\x1e\n" +
	"\x1aTRANSPORT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TRANSPORT_TYPE_WALKING\x10\x01\x12\x1a\n" +
	"\x16TRANSPORT_TYPE_BICYCLE\x10\x02\x12\x16\n" +
	"\x12TRANSPORT_TYPE_BUS\x10\x032\x8f\x01\n" +
	"\vTourService\x12?\n" +
	"\n" +
	"CreateTour\x12\x17.tour.CreateTourRequest\x1a\x18.tour.CreateTourResponse\x12?\n" +
	"\n" +
	"DeleteTour\x12\x17.tour.DeleteTourRequest\x1a\x18.tour.DeleteTourResponseB\x1bZ\x19tour.xws.com/proto/tourpbb\x06proto3"

var (
	file_proto_tour_proto_rawDescOnce sync.Once
	file_proto_tour_proto_rawDescData []byte
)

func file_proto_tour_proto_rawDescGZIP() []byte {
	file_proto_tour_proto_rawDescOnce.Do(func() {
		file_proto_tour_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tour_proto_rawDesc), len(file_proto_tour_proto_rawDesc)))
	})
	return file_proto_tour_proto_rawDescData
}

var file_proto_tour_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_tour_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_tour_proto_goTypes = []any{
	(TourStatus)(0),               // 0: tour.TourStatus
	(TourDifficulty)(0),           // 1: tour.TourDifficulty
	(TransportType)(0),            // 2: tour.TransportType
	(*Tour)(nil),                  // 3: tour.Tour
	(*CreateTourRequest)(nil),     // 4: tour.CreateTourRequest
	(*CreateTourResponse)(nil),    // 5: tour.CreateTourResponse
	(*DeleteTourRequest)(nil),     // 6: tour.DeleteTourRequest
	(*DeleteTourResponse)(nil),    // 7: tour.DeleteTourResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_proto_tour_proto_depIdxs = []int32{
	1,  // 0: tour.Tour.difficulty:type_name -> tour.TourDifficulty
	0,  // 1: tour.Tour.status:type_name -> tour.TourStatus
	8,  // 2: tour.Tour.published_at:type_name -> google.protobuf.Timestamp
	8,  // 3: tour.Tour.archived_at:type_name -> google.protobuf.Timestamp
	2,  // 4: tour.Tour.transport_type:type_name -> tour.TransportType
	1,  // 5: tour.CreateTourRequest.difficulty:type_name -> tour.TourDifficulty
	2,  // 6: tour.CreateTourRequest.transport_type:type_name -> tour.TransportType
	3,  // 7: tour.CreateTourResponse.tour:type_name -> tour.Tour
	4,  // 8: tour.TourService.CreateTour:input_type -> tour.CreateTourRequest
	6,  // 9: tour.TourService.DeleteTour:input_type -> tour.DeleteTourRequest
	5,  // 10: tour.TourService.CreateTour:output_type -> tour.CreateTourResponse
	7,  // 11: tour.TourService.DeleteTour:output_type -> tour.DeleteTourResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_tour_proto_init() }
func file_proto_tour_proto_init() {
	if File_proto_tour_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tour_proto_rawDesc), len(file_proto_tour_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tour_proto_goTypes,
		DependencyIndexes: file_proto_tour_proto_depIdxs,
		EnumInfos:         file_proto_tour_proto_enumTypes,
		MessageInfos:      file_proto_tour_proto_msgTypes,
	}.Build()
	File_proto_tour_proto = out.File
	file_proto_tour_proto_goTypes = nil
	file_proto_tour_proto_depIdxs = nil
}
