// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/followers.proto

package followerspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FolloweeId    string                 `protobuf:"bytes,2,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_proto_followers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_followers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_proto_followers_proto_rawDescGZIP(), []int{0}
}

func (x *FollowRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *FollowRequest) GetFolloweeId() string {
	if x != nil {
		return x.FolloweeId
	}
	return ""
}

type FollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResponse) Reset() {
	*x = FollowResponse{}
	mi := &file_proto_followers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResponse) ProtoMessage() {}

func (x *FollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_followers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResponse.ProtoReflect.Descriptor instead.
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return file_proto_followers_proto_rawDescGZIP(), []int{1}
}

func (x *FollowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_proto_followers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_followers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_proto_followers_proto_rawDescGZIP(), []int{2}
}

func (x *UserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersResponse) Reset() {
	*x = UsersResponse{}
	mi := &file_proto_followers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersResponse) ProtoMessage() {}

func (x *UsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_followers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersResponse.ProtoReflect.Descriptor instead.
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_followers_proto_rawDescGZIP(), []int{3}
}

func (x *UsersResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_proto_followers_proto protoreflect.FileDescriptor

const file_proto_followers_proto_rawDesc = "" +
	"\n" +
	"\x15proto/followers.proto\x12\tfollowers\"Q\n" +
	"\rFollowRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12\x1f\n" +
	"\vfollowee_id\x18\x02 \x01(\tR\n" +
	"followeeId\"*\n" +
	"\x0eFollowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"&\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"*\n" +
	"\rUsersResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds2\xde\x02\n" +
	"\x10FollowersService\x12=\n" +
	"\x06Follow\x12\x18.followers.FollowRequest\x1a\x19.followers.FollowResponse\x12?\n" +
	"\bUnfollow\x12\x18.followers.FollowRequest\x1a\x19.followers.FollowResponse\x12@\n" +
	"\fGetFollowing\x12\x16.followers.UserRequest\x1a\x18.followers.UsersResponse\x12@\n" +
	"\fGetFollowers\x12\x16.followers.UserRequest\x1a\x18.followers.UsersResponse\x12F\n" +
	"\x12GetRecommendations\x12\x16.followers.UserRequest\x1a\x18.followers.UsersResponseB_Z]github.com/zopuu/soa-team-20/Backend/services/followers_service/proto/followerspb;followerspbb\x06proto3"

var (
	file_proto_followers_proto_rawDescOnce sync.Once
	file_proto_followers_proto_rawDescData []byte
)

func file_proto_followers_proto_rawDescGZIP() []byte {
	file_proto_followers_proto_rawDescOnce.Do(func() {
		file_proto_followers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_followers_proto_rawDesc), len(file_proto_followers_proto_rawDesc)))
	})
	return file_proto_followers_proto_rawDescData
}

var file_proto_followers_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_followers_proto_goTypes = []any{
	(*FollowRequest)(nil),  // 0: followers.FollowRequest
	(*FollowResponse)(nil), // 1: followers.FollowResponse
	(*UserRequest)(nil),    // 2: followers.UserRequest
	(*UsersResponse)(nil),  // 3: followers.UsersResponse
}
var file_proto_followers_proto_depIdxs = []int32{
	0, // 0: followers.FollowersService.Follow:input_type -> followers.FollowRequest
	0, // 1: followers.FollowersService.Unfollow:input_type -> followers.FollowRequest
	2, // 2: followers.FollowersService.GetFollowing:input_type -> followers.UserRequest
	2, // 3: followers.FollowersService.GetFollowers:input_type -> followers.UserRequest
	2, // 4: followers.FollowersService.GetRecommendations:input_type -> followers.UserRequest
	1, // 5: followers.FollowersService.Follow:output_type -> followers.FollowResponse
	1, // 6: followers.FollowersService.Unfollow:output_type -> followers.FollowResponse
	3, // 7: followers.FollowersService.GetFollowing:output_type -> followers.UsersResponse
	3, // 8: followers.FollowersService.GetFollowers:output_type -> followers.UsersResponse
	3, // 9: followers.FollowersService.GetRecommendations:output_type -> followers.UsersResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_followers_proto_init() }
func file_proto_followers_proto_init() {
	if File_proto_followers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_followers_proto_rawDesc), len(file_proto_followers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_followers_proto_goTypes,
		DependencyIndexes: file_proto_followers_proto_depIdxs,
		MessageInfos:      file_proto_followers_proto_msgTypes,
	}.Build()
	File_proto_followers_proto = out.File
	file_proto_followers_proto_goTypes = nil
	file_proto_followers_proto_depIdxs = nil
}
